# Config file for automatic testing at travis-ci.org

sudo: false
language: python
matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
    - python: 3.8
      env: TOX_ENV=py38
    - os: osx
      language: generic
      osx_image: xcode11 # Python 3.7.4 running on macOS 10.14.4
      install: pip3 install --upgrade tox pytest
      env: TOX_ENV=py37
      script: tox -e $TOX_ENV
    - python: 3.7
      dist: xenial
      env: TOX_ENV=coverage
      install:
        - pip install --upgrade coverage pytest
        - pip install .
      script:
        - coverage run --source ufolint -m py.test
        - coverage report -m
      after_success:
        - bash <(curl -s https://codecov.io/bash)

script: tox -e $TOX_ENV

install:
  - pip install --upgrade tox pytest

notifications:
  email: false
